---
- name: Playbook for Bring UP ACI Fabric
  hosts: "192.168.1.144"
  connection: local
  gather_facts: no
  
  
# ============================================================================================================================================================
# Import Fabric Configuration Files
# ============================================================================================================================================================

  vars:
    
    #config_file: "./Fabric01/ACI_fabric.yml"
    snapshot_tag: "1001" # must be set by AWX
    ansible_host: "192.168.1.144"
    username: "admin"
    password: "cisco123"
  tasks:



# ============================================================================================================================================================
# Take a snaphot of current configuration
# ============================================================================================================================================================

    - name: Create a Snapshot
      aci_config_snapshot:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        export_policy: config_backup
        max_count: 10
        description: Backups taken before new configs are applied.
        validate_certs: "false"
      delegate_to: localhost
      tags: always,snapshot


# ============================================================================================================================================================
# Switch Provisioning
# >> GUI >> Fabric > Fabric Membership
# ============================================================================================================================================================
    - name: import Switchs csv
      csv_to_facts:
        src: '{{ playbook_dir }}/Fabric01/switches.csv'
      #when: switchs is defined
      tags: switchs

    - name: Add fabric node
      aci_fabric_node:
        validate_certs: "false"
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        serial: "{{ item.serial }}"
        node_id: "{{ item.nodeId }}"
        switch: "{{ item.name }}"
        state: present
      delegate_to: localhost
      loop: '{{ spreadsheet }}'
      loop_control:
        pause: 1
      tags: switchs
    
# ============================================================================================================================================================
# tenant  Provisioning
# Add new Tenant
# ============================================================================================================================================================
    - name: import tentant csv
      csv_to_facts:
        src: '{{ playbook_dir }}/Fabric01/tenant.csv'
      tags: tenant

    - name: Add a new tenant
      aci_tenant:
        validate_certs: "false"
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        tenant: "{{ item.name }}"
        description: "{{ item.description }}"
        state: present
      delegate_to: localhost
      loop: '{{ spreadsheet }}'
      loop_control:
        pause: 1
      tags: tenant

# ============================================================================================================================================================
# VRF  Provisioning
# Add new VRF
# ============================================================================================================================================================
    - name: import vrf csv
      csv_to_facts:
        src: '{{ playbook_dir }}/Fabric01/vrf.csv'
      tags: vrf

    
    - name: Add a new VRF to a tenant
      aci_vrf:
        validate_certs: "false"
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vrf: "{{ item.name }}"
        tenant: "{{ item.tenant }}"
        descr: "{{ item.description }}"
        policy_control_preference: enforced
        policy_control_direction: ingress
        state: present
      delegate_to: localhost
      loop: '{{ spreadsheet }}'
      loop_control:
        pause: 1
      tags: vrf
