---
- name: Playbook for Bring UP ACI Fabric
  hosts: "192.168.1.144"
  connection: local
  gather_facts: no
  
  
# ============================================================================================================================================================
# Import Fabric Configuration Files
# ============================================================================================================================================================

  vars:
    
    #config_file: "./Fabric01/ACI_fabric.yml"
    snapshot_tag: "1001" # must be set by AWX
    ansible_host: "192.168.1.144"
    username: "admin"
    password: "cisco123"
    
    
  tasks:

    - name: wait
      wait_for: timeout=3
      
      
    - name: PRE-SNAPSHOT 
      aci_rest:
        validate_certs: no
        use_proxy: no
        hostname: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        method: post
        path: /api/mo/uni.json
        content: |
         {"configExportP":{"attributes":{"dn":"uni/fabric/configexp-PRE-toto",
         "name":"PRE-toto","snapshot":"true","adminSt":"triggered","descr":"toto"}
      tags: always,snapshot



 
