---
- name: Playbook for Bring UP ACI Fabric
  hosts: localhost
  connection: local
  gather_facts: no

  
# ============================================================================================================================================================
# Import Fabric Configuration Files
# ============================================================================================================================================================

  vars:
    config_file: "./Fabric01/ACI_fabric.yml"
    snapshot_tag: "1001" # must be set by AWX

  tasks:
    - name: Import Main configuration file
      include_vars:
        file: "{{ config_file }}" # need to use a variable to set correct path
      tags: always,vars


# ============================================================================================================================================================
# Take a snaphot of current configuration
# ============================================================================================================================================================

    - name: Create a Snapshot
      aci_config_snapshot:
        host: "{{ apic_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        export_policy: config_backup
        max_count: 10
        description: Backups taken before new configs are applied.
        validate_certs: "false"
      delegate_to: localhost
      tags: always,snapshot


# ============================================================================================================================================================
# Switch Provisioning
# >> GUI >> Fabric > Fabric Membership
# ============================================================================================================================================================

    - name: Add fabric node
      aci_fabric_node:
        host: "{{ apic_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        serial: {{ item.serial }}
        node_id: {{ item.nodeId }}
        switch: {{ item.name }}
        state: present
      delegate_to: localhost
      with_items: "{{ switchs }}"
      loop_control:
        pause: 1
      when: switchs is defined
      tags: switchs
    
