---
- name: check csv loop example
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name:  import csv
      csv_to_facts:
        src: '{{ playbook_dir }}/Fabric01/fw_list.csv'
#    - name: "read csv"
#      debug: msg= "{{ item.sno }}"
#      loop: '{{ spreadsheet }}'
