---
- name: Configure Enhanced LAG Policy
  hosts: "192.168.1.144"
  connection: local
  gather_facts: no
  

  vars:
    
    #config_file: "./Fabric01/ACI_fabric.yml"
    snapshot_tag: "1001" # must be set by AWX
    ansible_host: "192.168.1.144"
    username: "admin"
    password: "cisco123"
  
  tasks:
# VMM EPG Enhanced LAG


    - name: import epg to modifie csv
      csv_to_facts:
        src: '{{ playbook_dir }}/vmmelag.csv'
      tags: vrni



    - name: Activate Enhanced LAG on EPG via REST
      aci_rest:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        path: /api/mo/uni.json
        method: post
        content: |
          {"fvAEPg":{"attributes":{"annotation":"","descr":"","dn":"uni/tn-tn-vmm/ap-ap-vmm/epg-vmm-epg02","exceptionTag":"",
          "floodOnEncap":"disabled","fwdCtrl":"","isAttrBasedEPg":"no","matchT":"AtleastOne","name":"vmm-epg02","nameAlias":"",
          "pcEnfPref":"unenforced","prefGrMemb":"exclude","prio":"unspecified"},
          "children":[{"fvRsDomAtt":{"attributes":{"annotation":"","classPref":"encap","delimiter":"","encap":"vlan-1002",
          "encapMode":"auto","epgCos":"Cos0","epgCosPref":"disabled","instrImedcy":"lazy","lagPolicyName":"","netflowDir":"both",
          "netflowPref":"disabled","primaryEncap":"unknown","primaryEncapInner":"unknown","resImedcy":"immediate",
          "secondaryEncapInner":"unknown","switchingMode":"native","tDn":"uni/vmmp-VMware/dom-vmm-dvs001","untagged":"no"},
          "children":[{"vmmSecP":{"attributes":{"allowPromiscuous":"reject","annotation":"","descr":"","forgedTransmits":"reject",
          "macChanges":"reject","name":"","nameAlias":"","ownerKey":"","ownerTag":""}}},
          {"fvAEPgLagPolAtt":{"attributes":{"annotation":""},
          "children":[{"fvRsVmmVSwitchEnhancedLagPol":{"attributes":{"annotation":"",
          "tDn":"uni/vmmp-VMware/dom-vmm-dvs001/vswitchpolcont/enlacplagp-lagNX"}}}]}}]}},
          {"fvRsCustQosPol":{"attributes":{"annotation":"","tnQosCustomPolName":""}}},
          {"fvRsBd":{"attributes":{"annotation":"","tnFvBDName":"vmm-bd01"}}}]}}
         
      delegate_to: localhost
      loop: '{{ spreadsheet }}'
      loop_control:
        pause: 1
      tags: vrni

  
